### ISSUE TITLE
Great discovery !

### ISSUE THREAD

**Issue by bluetyphoon77** [laliux/telegram-crypto-alerts#3]
Hi Laliux ! I remember we talked whn I was testing crypto signals and stochrsi ;) You helped...
It's great you brought the telegram part for configuration !!!!
I will try it asap ;)
Btw, would it be possible to hire your services just for writing a simple script sending weekly rsi signal over btcusdt when it reaches a specific level, with ta-lib or open source api ? I would like to learn to start from a basic working template ;) thanks

**Comment by laliux** [comment]
Hey @bluetyphoon77 

This repo is very outdated, please use the code on original repo, all my changes are there.

About the script you need, lets talk in discord :)
